apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: nginx
        image: harbor.clab.ai/oss/nginx:1.27.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        ports:
        - containerPort: 80